substitutions:
  device_name: "powmr-inverter"
  node_name: "PowMr Inverter"
  node_id: powmr_inverter
  inverter_tx_pin: GPIO16
  inverter_rx_pin: GPIO17
  pzem_tx_pin: GPIO1
  pzem_rx_pin: GPIO3

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

packages:
  main: !include powmr-inverter/main.yaml
  # You can replace next 2 lines with your common configs for all devices
  common_system: !include includes/common_system.yaml
  common_sensors: !include includes/common_sensors.yaml

logger:
  level: WARN
  logs:
    component: ERROR # Fix for issue #4717 "Component xxxxxx took a long time for an operation"

time:
  - platform: homeassistant
    id: hass_time

#web_server:
#  port: 80
#  ota: false


